# Generated by Django 4.1.3 on 2022-11-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_alter_timeinterval_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEnroll',
        ),
    ]
