# Generated by Django 4.1.2 on 2022-11-15 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_userenroll_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinstance',
            name='class_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_offering', to='classes.classoffering'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='class_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classoffering'),
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='class_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classoffering'),
        ),
        migrations.AlterField(
            model_name='userenroll',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classinstance'),
        ),
        migrations.AlterField(
            model_name='userenroll',
            name='class_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classoffering'),
        ),
    ]
